site_name: AllCloudThings

nav: 
  - Home: index.md
  # - Cloud-Computing: cloud-computing.md 

# #Cloud-Providers
# AWS Related Docs 
  - Learn-aws: 
    - AWS-Interview-Prep: cloud-providers/learn-aws/aws-interview-prep.md
    - AWS-Services: cloud-providers/learn-aws/aws-services.md  


# GCP Related Docs
  - Learn-GCP:
    - GCP-Interview-Prep: cloud-providers/learn-gcp/gcp-interview-prep.md
    - GCP-Services: cloud-providers/learn-gcp/gcp-services.md


# # Azure Related Docs 
  - Learn-Azure:
    - Azure-Interview-Prep: cloud-providers/learn-azure/azure-interview-prep.md
    - Azure-Services: cloud-providers/learn-azure/azure-services.md  


# CI-CD || Observability || Security || Tools 
  - More: 
    - CI-CD: 
      - Jenkins: More/ci-cd/what-is-jenkins.md
    - Observability:
      - What is Observability:  more/observability/what-is-observability.md 
    # - Security:
    #   - Cybersecurity: What-is-cybersecurity.md
    #   - Cybersecurity-tools: Cybersecurity-tools.md  
    - Tools:
      - List-of-Tools: more/tools/tooling.md  


# Infra-As-Code Tools and More
  - Infra-as-Code:
      - Infra-as-Code: infra-as-code/infra-as-code.md
      - Ansible: infra-as-code/ansible.md
      - Pulumi: infra-as-code/pulumi.md
      - Terraform: infra-as-code/terrform.md

# Everything about Containers here
  - Containers:
    - Kubernetes: containers/Kubernetes/what-is-kubernetes.md
    - Docker: containers/Docker/what-is-docker.md

theme: material

favicon: img/favicon.ico

